name: Shell quality checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: shell-quality-${{ github.ref == 'refs/heads/main' && 'main' || github.run_id }}
  cancel-in-progress: ${{ github.ref == 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  shell-quality:
    name: shell-quality
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install system dependencies
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ca-certificates curl jq

      - name: Install shell tooling
        run: |
          set -euo pipefail
          ./scripts/ci/install-shell-tools.sh

      - name: Run shell quality gate
        run: |
          set -euo pipefail
          ./scripts/ci/check-shell-quality.sh

      - name: Upload shell quality reports
        if: always()
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: shell-quality-reports
          path: reports/
          if-no-files-found: ignore
