name: Shell quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  shell-quality:
    name: shell quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y bats shellcheck curl ca-certificates busybox

      - name: Install shfmt
        env:
          SHFMT_VERSION: "3.9.2"
        run: |
          set -euo pipefail
          curl -sSfL "https://github.com/mvdan/sh/releases/download/v${SHFMT_VERSION}/shfmt_v${SHFMT_VERSION}_linux_amd64" -o shfmt
          sudo install -m 0755 shfmt /usr/local/bin/shfmt

      - name: Collect shell scripts
        run: |
          set -euo pipefail
          git ls-files | while read -r file; do
            if [ ! -f "$file" ]; then
              continue
            fi
            if head -n 1 "$file" | grep -Eq '^#!.*\\b(sh|bash)\\b'; then
              echo "$file"
            fi
          done | sort -u > shell-files.txt
          if [ ! -s shell-files.txt ]; then
            echo "No shell scripts found to check" >&2
            exit 1
          fi
          cat shell-files.txt

      - name: Run shellcheck
        run: |
          set -euo pipefail
          xargs -a shell-files.txt -r shellcheck -s sh

      - name: Check formatting with shfmt
        run: |
          set -euo pipefail
          xargs -a shell-files.txt -r shfmt -d -i 2 -bn -ci -sr

      - name: Run Bats tests
        env:
          BATS_SHELL: /bin/sh
        run: bats tests

  post-release-verify:
    name: Post-release verify
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: No-op verification
        run: echo "Post-release verification is not required for pull requests."
