name: OpenWrt E2E

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: read

jobs:
  e2e-openwrt:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'e2e'))
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    env:
      ARTIFACT_DIR: ${{ runner.temp }}/openwrt-e2e-artifacts

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qemu-system-x86 expect

      - name: Run OpenWrt E2E backup test
        run: |
          bash tests/e2e/run_openwrt_e2e.sh

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-e2e-artifacts
          path: ${{ env.ARTIFACT_DIR }}
