name: Shell quality checks

on:
  push:
  pull_request:

concurrency:
  group: shell-quality-${{ github.ref == 'refs/heads/main' && 'main' || github.run_id }}
  cancel-in-progress: ${{ github.ref == 'refs/heads/main' }}

jobs:
  shell-quality:
    name: Shell quality
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Cache shell tooling
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.cache/openwrt-toolkit
          key: shell-tools-${{ runner.os }}-${{ hashFiles('scripts/ci/install-shell-tools.sh') }}
          restore-keys: |
            shell-tools-${{ runner.os }}-

      - name: Install dependencies
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends jq ca-certificates

      - name: Install shell tooling
        shell: bash
        run: ./scripts/ci/install-shell-tools.sh

      - name: Run quality checks via Makefile
        run: make all

      - name: Upload ShellCheck report
        if: always()
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: shellcheck-report
          path: |
            reports/shellcheck.json
            reports/shellcheck.txt
            reports/unquoted-variables.txt
            reports/unsafe-eval.txt
            reports/shebang-violations.txt
            reports/shell-files.txt
          if-no-files-found: ignore

      - name: Upload shfmt patch
        if: always()
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: shfmt-report
          path: reports/shfmt.patch
          if-no-files-found: ignore
